/* Generated By:JavaCC: Do not edit this line. InfixToPrefixConstants.java */
package vn.edu.vnu.uet.quannk_56.scientific_research;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface InfixToPrefixConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int LPAREN = 6;
  /** RegularExpression Id. */
  int RPAREN = 7;
  /** RegularExpression Id. */
  int ASSIGN = 8;
  /** RegularExpression Id. */
  int LT = 9;
  /** RegularExpression Id. */
  int GT = 10;
  /** RegularExpression Id. */
  int COLON = 11;
  /** RegularExpression Id. */
  int EQ = 12;
  /** RegularExpression Id. */
  int LE = 13;
  /** RegularExpression Id. */
  int GE = 14;
  /** RegularExpression Id. */
  int NE = 15;
  /** RegularExpression Id. */
  int SC_OR = 16;
  /** RegularExpression Id. */
  int SC_AND = 17;
  /** RegularExpression Id. */
  int PLUS = 18;
  /** RegularExpression Id. */
  int MINUS = 19;
  /** RegularExpression Id. */
  int STAR = 20;
  /** RegularExpression Id. */
  int SLASH = 21;
  /** RegularExpression Id. */
  int BIT_AND = 22;
  /** RegularExpression Id. */
  int BIT_OR = 23;
  /** RegularExpression Id. */
  int XOR = 24;
  /** RegularExpression Id. */
  int REM = 25;
  /** RegularExpression Id. */
  int LSHIFT = 26;
  /** RegularExpression Id. */
  int IMPLICATION = 27;
  /** RegularExpression Id. */
  int Const = 28;
  /** RegularExpression Id. */
  int Var = 29;
  /** RegularExpression Id. */
  int Number = 30;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\"\\f\"",
    "\"(\"",
    "\")\"",
    "\"=\"",
    "\"<\"",
    "\">\"",
    "\":\"",
    "\"==\"",
    "\"<=\"",
    "\">=\"",
    "\"!=\"",
    "\"||\"",
    "\"&&\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\"&\"",
    "\"|\"",
    "\"^\"",
    "\"%\"",
    "\"<<\"",
    "\"=>\"",
    "<Const>",
    "<Var>",
    "<Number>",
  };

}
